### ISSUE TITLE
Option to show task description under the title

### ISSUE THREAD

**Issue by artizirk** [gwleuverink/clickup-time-tracker#17]
Would it be possible to add a option to show task description under the task title in the calendar view? Clicking on the task to view it is kinda tedious.

**Comment by gwleuverink** [comment]
Hi, yeah I think this would be a useful addition. I don't want to clutter the main calendar view though, so I'm thinking about using a popover on hover. Would this cover your need?

<img width="312" alt="image" src="https://user-images.githubusercontent.com/17123491/163954895-7fc49737-317b-40db-a444-0676dc57b19d.png">

**Comment by artizirk** [comment]
That would also work

T, 19. aprill 2022 11:02 Willem Leuverink ***@***.***>
kirjutas:

**Comment by gwleuverink** [comment]
Cool. It's added in #18. I've got a couple of things left to do on the roadmap before I publish a new release.
In the mean time you can pull in the main branch to fool around with it if you like 👍
