### ISSUE TITLE
Task list response can't be decoded when a task contains a double quote

### ISSUE THREAD

**Issue by irenavi77** [gwleuverink/clickup-time-tracker#29]
Can not refresh card list at all. some issue with connection to click up?
![SharedScreenshot](https://user-images.githubusercontent.com/112762942/188271541-cf854677-2ae7-419b-b47f-30cf8a3b843c.jpg)

**Comment by gwleuverink** [comment]
Hi @irenavi77, thanks for your feedback.

Normally I'd expect an error message so I have a suspicion the process was still working on the background. 

When your organization has a lot of tasks, fetching the entire list can take a while. The API doesn't allow fuzzy searching so all tasks are cached on your machine. It could be you have to wait a bit longer.

If that doesn't work I have noticed an issue on some networks. Could you also try switching to a different network and try again?

If this doesn't resolve your issue please let me know

**Comment by irenavi77** [comment]
Hi @gwleuverink ! Thank you for quick response. Tried with another WIFI connection (private). After 1 hour it still refreshing. I have about 100 tasks. 
Any thoughts? The time tracker looks amazing, I hope you'll find the solution.

**Comment by HugoHeneault** [comment]
Double check your token, we had an issue with it and it failed silently ;)

**Comment by gwleuverink** [comment]
Hmm yes I just verified there is no error message shown. It should do that. @HugoHeneault thanks for letting me know.

I think there should be validation of the token & team id inside the settings screen that actually tests if the entered values are o.k. I'll put that on the shortlist.

@irenavi77 do you still have issues after checking the team id?

**Comment by MichielBier** [comment]
This also sometimes happens for me. Only way to fix it is to fully close and restart the application for me.

**Comment by irenavi77** [comment]
Thanks for your feedback. I think the API token and the team ID is OK, cause I see the records from Clickup and I can rewrite them and they synchronize back to CU. But still can not create the new one.

**Comment by gwleuverink** [comment]
Hmm that is weird. Could you send me your IP address? I'll check our error tracker to pinpoint the issue

If you don't want to share that here you can send it by mail to willem@leuver.ink

**Comment by gwleuverink** [comment]
Hi @irenavi77 I just received your email. 

It looks like one of the tasks contains an unexpected character which breaks the json decoding we do on our side. 

Since we don't collect any data except stack traces I can't pinpoint exactly what it is, but maybe you can help me find it so I can mitigate the issue.

The character seems to be located somewhere on the first page. Could you try and fetch the data manually & pinpoint exactly what character is causing the issue when decoding the response?

This url returns the unexpected character: https://api.clickup.com/api/v2/team/{replace-with-team-id}/task?page=0&archived=false&include_closed=false

**Comment by irenavi77** [comment]
Hi @gwleuverink 
It worked!
I checked all the tasks and remove characters  # and " from the name of the task. One of them did the problem. I dont know which one. 
Thank you very much!!! Hope it will be useful for another users :)

**Comment by gwleuverink** [comment]
That's great! I have a sneaking suspicion that the double quote was the culprit. I'll update the issue title accordingly
