### ISSUE TITLE
Display list name below task title in task select dropdown

### ISSUE THREAD

**Issue by HugoHeneault** [gwleuverink/clickup-time-tracker#30]
Hello there, 

We juste discovered your tool and it is awesome!

We have many tasks (by sprints) with the same name and would love to have lists name appearing on the list. 

Is it possible?

We might be able to craft a PR if you'd like to.

Thanks

**Comment by gwleuverink** [comment]
Hi @HugoHeneault Glad you like the tool.

Yes this is definitely possible. A couple of people have asked for this already. 

Right now I'm focusing my efforts on getting this app on the Mac App Store. When that is done I'll go full steam ahead with quality of life improvements such as these.

If you need this addition sooner than I can accommodate I'll gladly accept a PR.

---------------------------

I use this UI library: https://www.naiveui.com/en-US/os-theme/components/select#custom-option.vue
I was thinking about displaying the list name on a separate line under the task title (maybe in a smaller font & slightly lighter gray)

**Comment by gwleuverink** [comment]
Hi @HugoHeneault This request is pending the next release (probably in a week or so)

![Image](https://user-images.githubusercontent.com/17123491/192795794-9676ae86-317d-4535-a4a6-261aee7f86e5.png)

**Comment by HugoHeneault** [comment]
Hello there 👋 

Do you have some news about a release date?

**Comment by gwleuverink** [comment]
Hey @HugoHeneault We've been running the 1.1 version internally. I've got to admit that releasing a build slipped my mind. Silly me. I'll see about releasing it soon

**Comment by HugoHeneault** [comment]
Awesome. 🎉

**Comment by gwleuverink** [comment]
@HugoHeneault You can download V1.1 now. This request is included in the new release.
