### ISSUE TITLE
Display total tracked hours in day header

### ISSUE THREAD

**Issue by HugoHeneault** [gwleuverink/clickup-time-tracker#31]
It would be awesome to get the daily toyal in day header, as seen in Paymo :)

<img width="227" alt="image" src="https://user-images.githubusercontent.com/4112256/188593407-9fd03186-c0ce-44cb-87be-27ad90ecf48d.png">

**Comment by gwleuverink** [comment]
Hi @HugoHeneault. Thanks for this suggestion. I think it's pretty low hanging fruit. I've added it to the shortlist.

I might hide it behind a user preference toggle so the UI stays minimal for people who don't have need for this addition

**Comment by gwleuverink** [comment]
Coming up next:

![image](https://user-images.githubusercontent.com/17123491/199698614-e93be50a-dd4d-4104-a4e5-cfeefd24ad1d.png)

**Comment by gwleuverink** [comment]
@HugoHeneault Also released with v1.1 🎉
